version: '3'

services:
  fivem:
    image: onvrb/fivem
    container_name: fivem
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - "./fivem:/config"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
