#!/bin/sh

if ! find . -mindepth 1 | read; then
  echo -e "Creating default configs...\n"
  cp -r /opt/cfx-server-data/* /config
  RCON_PASS="${RCON_PASSWORD-$(tr -dc 'a-zA-Z0-9' < /dev/urandom | head -c 16)}"
  sed -i "s/{RCON_PASS}/${RCON_PASS}/g" /config/cfgs/server.cfg;
  echo "----------------------------------------------"
  echo "Your RCON password is set to: ${RCON_PASS}"
  echo -e "----------------------------------------------\n"
fi

exec /opt/cfx-server/ld-musl-x86_64.so.1  \
  --library-path "/usr/lib/v8/:/lib/:/usr/lib/" \
  -- \
  /opt/cfx-server/FXServer \
  +set citizen_dir /opt/cfx-server/citizen/ \
  +set txDataPath /config/txData/ \
  # +exec /config/cfgs/server.cfg \ #comment to run txAdmin
  $*
